# Generated by Django 4.2.15 on 2024-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_failedprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_str',
            field=models.CharField(blank=True, help_text='Task ID as string', max_length=255, null=True, verbose_name='ID String'),
        ),
    ]
