# Generated by Django 4.2.15 on 2024-09-26 16:05

from django.db import migrations

def populate_id_str(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    # Update each Task to set id_str as the string representation of id
    for task in Task.objects.all():
        task.id_str = str(task.id)
        task.save(update_fields=['id_str'])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_task_id_str'),
    ]

    operations = [
        migrations.RunPython(populate_id_str),
    ]
