# Generated by Django 4.2.15 on 2024-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projectgroup_project_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='z_index',
            field=models.IntegerField(default=-1, help_text='Zed Index of the project group'),
        ),
    ]
