# Generated by Django 4.2.15 on 2024-10-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectgroup_z_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='z_index',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='next_group',
            field=models.ForeignKey(blank=True, help_text='Next project group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_groups', to='projects.projectgroup'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='prev_group',
            field=models.ForeignKey(blank=True, help_text='Previous project group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_groups', to='projects.projectgroup'),
        ),
    ]
