# Generated by Django 4.2.15 on 2024-10-03 15:43

from django.db import migrations


def link_project_groups(apps, schema_editor):
    ProjectGroup = apps.get_model('projects', 'ProjectGroup')
    groups = list(ProjectGroup.objects.all())

    # Sort groups by id or any other field if needed
    groups.sort(key=lambda group: group.id)

    for i, group in enumerate(groups):
        prev_group = groups[i - 1] if i > 0 else None
        next_group = groups[i + 1] if i < len(groups) - 1 else None

        group.prev_group = prev_group
        group.next_group = next_group
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_projectgroup_z_index_projectgroup_next_group_and_more'),
    ]

    operations = [
        migrations.RunPython(link_project_groups),
    ]