# Generated by Django 4.2.15 on 2024-10-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_link_project_groups'),
        ('projects', '0031_reset_linked_connections'),
    ]

    operations = [
    ]
