# Generated by Django 4.2.15 on 2024-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_merge_20241003_1643'),
        ('projects', '0033_reset_linked_list'),
    ]

    operations = [
    ]
