# Generated by Django 4.2.15 on 2024-10-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_merge_0032_merge_20241003_1643_0033_reset_linked_list'),
        ('projects', '0035_reset_linked_list'),
    ]

    operations = [
    ]
