# Generated by Django 4.2.15 on 2024-10-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_merge_20241003_1748'),
        ('projects', '0037_reset_linked_list'),
    ]

    operations = [
    ]
