# Generated by Django 4.2.15 on 2024-10-04 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_reset_linked_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='next_group',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='prev_group',
        ),
        migrations.CreateModel(
            name='ProjectGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectgroup')),
                ('next_group', models.ForeignKey(blank=True, help_text="Next project group in the user's list", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_groups', to='projects.projectgrouplist')),
                ('prev_group', models.ForeignKey(blank=True, help_text="Previous project group in the user's list", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_groups', to='projects.projectgrouplist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
